config/routes.rb
Rails.application.routes.draw do
  root to: "admin_users#dashboard"
  devise_for :admin_users

  namespace :api do
    resources :movies
    resources :users, only: [:create]
    get '/:username/favorite_movies', to: 'users#favorite_movies'
    post '/movies/:id/set_favorite', to: 'movies#set_favorite'
  end

  namespace :admin do
    resources :movies
    resources :users, only: [:index, :show, :destroy]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :users_favorite_movies, dependent: :destroy
  has_many :users, through: :users_favorite_movies

  validates :name, :genres, :favorited, presence: true
  validates :year, presence: true, numericality: { only_integer: true }


  MOVIE_GENRES = [
    "Action",
    "Adventure",
    "Animation",
    "Biography",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Fantasy",
    "History",
    "Horror",
    "Musical",
    "Mystery",
    "Romance",
    "Sci-Fi",
    "Thriller",
    "War",
    "Western"
  ]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :users_favorite_movies, dependent: :destroy
  has_many :movies, through: :users_favorite_movies

  validates :username, presence: true, format: {with: /\A[a-zA-Z0-9_]+\z/ }
end

app/models/users_favorite_movie.rb
class UsersFavoriteMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController

  before_action :authenticate_admin_user!
  before_action :set_movie, except: [:index]

  def index
    @movies = Movie.all.order(created_at: :desc)
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to admin_movies_path, notice: 'Movie has been created successfully.'
    else
      render :new
    end
  end

  def show

  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    if @movie.update(movie_params)
      redirect_to admin_movies_path, notice: 'Movie has been updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    if @movie && @movie.destroy
      redirect_to admin_movies_path, notice: 'Movie has been deleted.'
    else
      render :index
    end
  end

  private

  def set_movie
    @movie = params[:id].present? ? Movie.find(params[:id]) : Movie.new
  end

  def movie_params
    params.require(:movie).permit(:name, :year, :director, :main_star, :description, :genres => [])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :set_user, except: [:index]

  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
  end

  def destroy
    if @user && @user.destroy
      redirect_to admin_users_path, notice: 'User has been deleted.'
    else
      render :index
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  before_action :authenticate_admin_user!

  def dashboard
  end
end

app/controllers/api/movies_controller.rb
class Api::MoviesController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @favorited_user_count = @movie.users_favorite_movies.count
  end

  def set_favorite
    movie = Movie.find(params[:id])
    user = User.find_by_username(params[:username])
    movie.users_favorite_movies.create(user: user)
    movie.favorited += 1
    movie.save
    render json: {status: 200, message: 'Added as favorite movie.'}
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  skip_before_action :verify_authenticity_token

  def create
    user = User.find_by(username: params[:username])
    if user.present?
      render json: {status: 409, message: 'User already exists.'}
    else
      User.create(username: params[:username])
      render json: {status: 201, message: 'New user has been created.'}
    end
  end

  def favorite_movies
    user = User.find_by_username(params[:username])
    @favorite_movies = user.movies
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authenticate_admin_user!
  before_action :set_movie, except: [:index]

  def index
    @movies = Movie.all.order(created_at: :desc)
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: 'Movie has been created successfully.'
    else
      render :new
    end
  end

  def show

  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    if @movie.update(movie_params)
      redirect_to movies_path, notice: 'Movie has been updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    if @movie && @movie.destroy
      redirect_to movies_path, notice: 'Movie has been deleted.'
    else
      render :index
    end
  end

  private

  def set_movie
    @movie = params[:id].present? ? Movie.find(params[:id]) : Movie.new
  end

  def movie_params
    params.require(:movie).permit(:name, :year, :director, :main_star, :description, :is_favorite, :genres => [])
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/movies/_form.html.erb
<%= form_for(@movie, url: @movie.persisted? ? admin_movie_path : admin_movies_path) do |form| %>
  <%= render partial: 'layouts/error_message', locals: { object: @movie } %>
  <div class="form-group">
    <%= form.label :name, class: 'control-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :genres, class: 'control-label' %> <br>
    <div class="check-box-parent-wrapper">
      <% Movie::MOVIE_GENRES.each do |genre| %>
        <div class="check-box-wrapper">
          <%= form.check_box :genres, {multiple: true}, genre, false %>
          <%= label_tag genre, genre %>
          <br>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :year, class: 'control-label' %>
    <%= form.select :year, Date.today.years_ago(125).year..Date.today.year, { :selected => Date.today.year }, { :multiple => false, class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label :director, class: 'control-label' %>
    <%= form.text_field :director, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :main_star, class: 'control-label' %>
    <%= form.text_field :main_star, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, class: 'control-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if current_page?(new_admin_movie_path) %>
      <%= form.submit 'Create Movie', class: 'btn btn-success' %>
    <% else %>
      <%= form.submit 'Update', class: 'btn btn-success' %>
    <% end %>
    <%= link_to 'Back', :back, class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/admin/movies/edit.html.erb
<div class="card">
  <div class="card-header">
    <h3>Add Movie</h3>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-8">
        <%= render 'form', movie: @movie %>
      </div>
    </div>
  </div>
</div>

app/views/admin/movies/index.html.erb
<%= link_to "Add Movie", new_admin_movie_path, class: "btn btn-dark", style: "float:right" %>
<h1>All Movies</h1>
<table class="table table-bordered" id="movies_list_table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th># times favorited</th>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  <% @movies.each do |movie| %>
    <tr>
      <td><%= link_to movie.name, edit_admin_movie_path(movie) %></td>
      <td><%= movie.year %></td>
      <td><%= movie.favorited %></td>
      <td>
        <%= link_to 'Delete',admin_movie_path(movie), method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<div>
  <%= link_to "Back", :back, class: "btn btn-dark" %>
</div>

app/views/admin/movies/new.html.erb
<div class="card">
  <div class="card-header">
    <h3>Add Movie</h3>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-8">
        <%= render 'form', movie: @movie %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<h1>All Users</h1>
<table class="table table-bordered" id="users_list_table">
  <thead>
  <tr>
    <th>Username</th>
    <th># favorited movies</th>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, admin_user_path(user) %></td>
      <td><%= user.users_favorite_movies.count %></td>
      <td>
        <%= link_to 'Delete',admin_user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<div>
  <%= link_to "Back", :back, class: "btn btn-dark" %>
</div>

app/views/admin/users/show.html.erb
<div class="card">
  <div class="card-header">
    <h2>User: <%= @user.username %></h2>
  </div>
  <div class="card-body">
    <h4>Favorited Movies:</h4>
    <ul class="movie-names">
      <% @user.users_favorite_movies.each do |favorited_movie| %>
        <li><%= favorited_movie.movie.name %></li>
      <% end %>
    </ul>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', :back, class: "btn btn-dark" %>
  </div>
</div>

app/views/admin_users/dashboard.html.erb
<div class="row">
  <div class="col-12">
    <h1>Admin Dashboard</h1>
  </div>
</div>

app/views/layouts/_error_message.html.erb
<div class="container-fluid" id="error_msg">
  <% if object.errors.full_messages.any? %>
    <% object.errors.full_messages.each do |error_message| %>
      <p class="alert alert-danger"> <%= error_message if object.errors.full_messages.first == error_message %> </p>
    <% break end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RorMovieApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- BOOTSTRAP -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Favorite Movie", root_path, class: "navbar-brand", id: 'hero_text' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if admin_user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <%= link_to 'Movies', admin_movies_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <%= link_to 'Users', admin_users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_admin_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  <% end %>
</nav>
<div class="container-fluid" id="flash_msg">
  <% flash.each do |key, value| %>
    <% if key == "alert" %>
      <%= content_tag(:div, value, class: "alert alert-danger") %>
    <% elsif key == "notice" %>
      <%= content_tag(:div, value, class: "alert alert-success") %>
    <% end %>
  <% end %>
</div>
<div class="container" id="main-div">
  <%= yield %>
</div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |form| %>
  <%= render partial: 'layouts/error_message', locals: { object: @movie } %>
  <div class="form-group">
    <%= form.label :name, class: 'control-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :genres, class: 'control-label' %> <br>
    <div class="check-box-parent-wrapper">
      <% Movie::MOVIE_GENRES.each do |genre| %>
        <div class="check-box-wrapper">
          <%= form.check_box :genres, {multiple: true}, genre, false %>
          <%= label_tag genre, genre %>
          <br>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :year, class: 'control-label' %>
    <%= form.select :year, Date.today.years_ago(125).year..Date.today.year, { :selected => Date.today.year }, { :multiple => false, class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label :director, class: 'control-label' %>
    <%= form.text_field :director, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :main_star, class: 'control-label' %>
    <%= form.text_field :main_star, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, class: 'control-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if current_page?(new_movie_path) %>
      <%= form.submit 'Create Movie', class: 'btn btn-success' %>
    <% else %>
      <%= form.submit 'Update', class: 'btn btn-success' %>
    <% end %>
    <%= link_to 'Back', :back, class: 'btn btn-dark' %>
  </div>
<% end %>